"""Constants for Lotus View Studio."""

DOMAIN = "lotus_view_studio"
LEGACY_DOMAIN = "lotus_visual"
URL_BASE = "/lotus_view_studio_static"
BRAND_URL = "/lotus_view_studio_brand"
VERSIONED_URL_BASE = "/lotus_view_studio_static_v"
VERSIONED_BRAND_URL = "/lotus_view_studio_brand_v"
LEGACY_URL_BASE = "/lotus_visual_static"
LEGACY_BRAND_URL = "/lotus_visual_brand"
PANEL_PATH = "lotus-view-studio"
PANEL_TITLE = "Lotus View Studio"
PANEL_ICON = "lotus:lotus"
